{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2021-3428",
			"ASSIGNER": "secalert@redhat.com"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1972621",
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=1972621",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://ubuntu.com/security/CVE-2021-3428",
					"name": "https://ubuntu.com/security/CVE-2021-3428",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://www.openwall.com/lists/oss-security/2021/03/17/1",
					"name": "https://www.openwall.com/lists/oss-security/2021/03/17/1",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "A flaw was found in the Linux kernel. A denial of service problem is identified if an extent tree is corrupted in a crafted ext4 filesystem in fs/ext4/extents.c in ext4_es_cache_extent. Fabricating an integer overflow, A local attacker with a special user privilege may cause a system crash problem which can lead to an availability threat."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2022-03-04T18:15Z",
	"lastModifiedDate": "2022-03-04T18:15Z"
}