{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2020-16125",
			"ASSIGNER": "cve@mitre.org"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1900314",
					"name": "https://bugs.launchpad.net/ubuntu/+source/gdm3/+bug/1900314",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://gitlab.gnome.org/GNOME/gdm/-/issues/642",
					"name": "https://gitlab.gnome.org/GNOME/gdm/-/issues/642",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://securitylab.github.com/advisories/GHSL-2020-202-gdm3-LPE-unresponsive-accounts-daemon",
					"name": "https://securitylab.github.com/advisories/GHSL-2020-202-gdm3-LPE-unresponsive-accounts-daemon",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "gdm3 versions before 3.36.2 or 3.38.2 would start gnome-initial-setup if gdm3 can't contact the accountservice service via dbus in a timely manner; on Ubuntu (and potentially derivatives) this could be be chained with an additional issue that could allow a local user to create a new privileged account."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2020-11-10T05:15Z",
	"lastModifiedDate": "2020-11-10T12:40Z"
}