{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2022-30284",
			"ASSIGNER": "cve@mitre.org"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://github.com/savon-noir/python-libnmap/releases",
					"name": "https://github.com/savon-noir/python-libnmap/releases",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://www.swascan.com/security-advisory-libnmap-2/",
					"name": "https://www.swascan.com/security-advisory-libnmap-2/",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://pypi.org/project/python-libnmap/",
					"name": "https://pypi.org/project/python-libnmap/",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "In the python-libnmap package through 0.7.2 for Python, remote command execution can occur (if used in a client application that does not validate arguments)."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2022-05-04T22:15Z",
	"lastModifiedDate": "2022-05-05T11:30Z"
}