{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2022-28470",
			"ASSIGNER": "cve@mitre.org"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": []
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://pypi.org/project/marcador/",
					"name": "https://pypi.org/project/marcador/",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "http://pypi.doubanio.com/simple/request",
					"name": "http://pypi.doubanio.com/simple/request",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://github.com/joajfreitas/marcador/issues/5",
					"name": "https://github.com/joajfreitas/marcador/issues/5",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "marcador package in PyPI 0.1 through 0.13 included a code-execution backdoor."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2022-05-08T20:15Z",
	"lastModifiedDate": "2022-05-09T12:12Z"
}