{
	"cve": {
		"data_type": "CVE",
		"data_format": "MITRE",
		"data_version": "4.0",
		"CVE_data_meta": {
			"ID": "CVE-2021-20273",
			"ASSIGNER": "cve@mitre.org"
		},
		"problemtype": {
			"problemtype_data": [
				{
					"description": [
						{
							"lang": "en",
							"value": "CWE-20"
						}
					]
				}
			]
		},
		"references": {
			"reference_data": [
				{
					"url": "https://bugzilla.redhat.com/show_bug.cgi?id=1936658",
					"name": "https://bugzilla.redhat.com/show_bug.cgi?id=1936658",
					"refsource": "MISC",
					"tags": []
				},
				{
					"url": "https://www.privoxy.org/announce.txt",
					"name": "https://www.privoxy.org/announce.txt",
					"refsource": "MISC",
					"tags": []
				}
			]
		},
		"description": {
			"description_data": [
				{
					"lang": "en",
					"value": "A flaw was found in privoxy before 3.0.32. A crash can occur via a crafted CGI request if Privoxy is toggled off."
				}
			]
		}
	},
	"configurations": {
		"CVE_data_version": "4.0",
		"nodes": []
	},
	"impact": {},
	"publishedDate": "2021-03-09T14:15Z",
	"lastModifiedDate": "2021-03-09T15:17Z"
}